[package]
name = "temperature_converter"
version = "0.1.0"
authors = ["ZeroTixDev <67355595+ZeroTixDev@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
